[package]
name = "wasm-module"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = { version = "0.2.92", features = ["serde-serialize"] }
serde_json = "1.0.120"
[lib]
crate-type = ["cdylib", "rlib"]

